[package]
name = "gribouille"
version = "0.0.1"
compiler = "0.14.2"
entrypoint = "lib.typ"
authors = ["Mickaël Canouil <pro@mickael.canouil.dev> (https://mickael.canouil.fr)"]
license = "MIT"
description = "A layered grammar of graphics for Typst."
repository = "https://github.com/mcanouil/gribouille"
homepage = "https://m.canouil.dev/gribouille"
keywords = ["plot", "chart", "visualisation", "grammar-of-graphics", "visualization"]
categories = ["visualisation", "visualization"]
exclude = ["tests", "examples"]
