-- Read the Typst compiler version from typst.toml and every `@preview/<name>:<version>`
-- import from src/deps.typ.
-- Validate that src/deps.typ is the sole @preview import site under src/, then
-- render docs/_variables.yml.

local util = require("util")

local M = {}

local function parse_compiler(source)
  local in_package = false
  for line in source:gmatch("([^\n]*)\n?") do
    local stripped = util.trim(line)
    if stripped:sub(1, 1) ~= "#" and stripped ~= "" then
      local header = stripped:match("^%[%s*([%w%.%-_]+)%s*%]$")
      if header then
        in_package = (header == "package")
      elseif in_package then
        local value = stripped:match("^compiler%s*=%s*\"([^\"]*)\"%s*$")
        if value then return value end
      end
    end
  end
  return nil
end

local function series(version)
  local major, minor = version:match("^(%d+)%.(%d+)")
  if not major then util.die("unexpected version format: " .. version) end
  return major .. "." .. minor
end

local function parse_imports(source)
  local imports = {}
  local order = {}
  for name, version in source:gmatch("@preview/([%w%-_]+):([%w%.%-]+)") do
    if not imports[name] then
      imports[name] = version
      order[#order + 1] = name
    elseif imports[name] ~= version then
      util.die(string.format(
        "src/deps.typ imports @preview/%s at two versions (%s and %s)",
        name, imports[name], version))
    end
  end
  return imports, order
end

local function validate_no_stray_imports(src_root, deps_path)
  for _, file in ipairs(util.find_typ_files(src_root)) do
    if file ~= deps_path then
      local content = util.read_file(file) or ""
      if content:match("@preview/[%w%-_]+:") then
        util.die(string.format(
          "%s imports an @preview/* package directly; re-export from deps.typ instead",
          file))
      end
    end
  end
end

local function yaml_escape(value)
  return (value:gsub("\"", "\\\""))
end

local function render_yaml(typst_version, deps, order)
  local lines = {
    "# Generated by tools/typstdoc/main.lua. Do not edit.",
    "typst:",
    string.format("  version: \"%s\"", yaml_escape(typst_version)),
    string.format("  series: \"%s\"", yaml_escape(series(typst_version))),
  }
  if #order == 0 then
    lines[#lines + 1] = "dependencies: {}"
  else
    lines[#lines + 1] = "dependencies:"
    for _, name in ipairs(order) do
      local version = deps[name]
      lines[#lines + 1] = string.format("  %s:", name)
      lines[#lines + 1] = string.format("    version: \"%s\"", yaml_escape(version))
      lines[#lines + 1] = string.format("    series: \"%s\"", yaml_escape(series(version)))
      lines[#lines + 1] = string.format(
        "    url: \"https://typst.app/universe/package/%s\"", name)
    end
  end
  return table.concat(lines, "\n") .. "\n"
end

function M.collect(opts)
  local toml_source = util.read_file(opts.toml)
    or util.die("cannot read " .. opts.toml)
  local typst_version = parse_compiler(toml_source)
    or util.die(opts.toml .. ": missing package.compiler")

  local deps_source = util.read_file(opts.deps_file)
    or util.die("cannot read " .. opts.deps_file)
  local imports, order = parse_imports(deps_source)

  validate_no_stray_imports(opts.src, opts.deps_file)

  return {
    typst_version = typst_version,
    dependencies = imports,
    order = order,
  }
end

function M.render(info)
  return render_yaml(info.typst_version, info.dependencies, info.order)
end

function M.summary(info)
  local parts = { "typst " .. info.typst_version }
  for _, name in ipairs(info.order) do
    parts[#parts + 1] = name .. " " .. info.dependencies[name]
  end
  return table.concat(parts, ", ")
end

return M
